require("caffesale.plugins-setup")
require("caffesale.core.options")
require("caffesale.core.colorscheme")
require("caffesale.core.keymaps")

-- plugins
require("caffesale.plugins.comment")
require("caffesale.plugins.nvim-tree")
require("caffesale.plugins.lualine")
require("caffesale.plugins.telescope")
require("caffesale.plugins.nvim-cmp")
require("caffesale.plugins.lsp.mason")
require("caffesale.plugins.lsp.lspsaga")
require("caffesale.plugins.lsp.lspconfig")
require("caffesale.plugins.lsp.null-ls")
require("caffesale.plugins.autopairs")
require("caffesale.plugins.treesitter")
require("caffesale.plugins.gitsigns")
require("caffesale.plugins.harpoon")
require("caffesale.plugins.undotree")
require("caffesale.plugins.bufferline")
require("caffesale.plugins.indent-blankline")
require("caffesale.plugins.symbols")
require("caffesale.plugins.todo")
require("caffesale.plugins.toggleterm")
require("caffesale.plugins.dap.mason-nvim-dap")
require("caffesale.plugins.dap.dap")
